Payroll/Payroll/Controllers/AttendenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.Controllers
{
    public class AttendenceController : Controller
    {
        // GET: Attendence
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EmployeeAttendence()
        {
            return View();
        }
    }
}

Payroll/Payroll/Controllers/AuthController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BusinessLayer.Auth;
using BusinessLayer;
using BusinessEntities;

namespace Payroll.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {

        [HttpGet]
        public ActionResult LogIn(string returnUrl)
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut("ApplicationCookie");
            var model = new LogInModel
            {
                ReturnUrl = returnUrl
            };

            return View(model);
        }


        [HttpPost]
        public ActionResult LogIn(LogInModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }


            IAuthService _ias = new AuthService();
            SpVerifyUserSel_Result isUserValidModel = _ias.VerifyUserSel(model.Email);
            SpVerifyEmployeeSel_Result isValidEmployee = _ias.verfiyEmployeeSel(model.Email);
            //User Login
            if (isUserValidModel != null)
            {
                var isPassworValid = ValidatePassword(model.Password, isUserValidModel.Password);
                // Don't do this in production!
                if (isPassworValid)
                {
                    var identity = new ClaimsIdentity(new[]
                        {
                            new Claim("DisplayName",isUserValidModel.FullName),
                            new Claim(ClaimTypes.Name, isUserValidModel.FullName),
                            new Claim(ClaimTypes.Email, isUserValidModel.Email),
                            new Claim("UserId", isUserValidModel.UserId.ToString()),
                            new Claim("ClientId", isUserValidModel.ClientId.ToString())
                        },
                        "ApplicationCookie");
                    var roles = _ias.UserRoleSel(isUserValidModel.UserId);
                    foreach (var userRole in roles)
                    {
                        identity.AddClaim(new Claim(ClaimTypes.Role, userRole.RoleName));
                    }
                    
                    //identity.AddClaim(new Claim(ClaimTypes.Role, "OmniUser"));
                    var ctx = Request.GetOwinContext();
                    var authManager = ctx.Authentication;

                    authManager.SignIn(identity);

                    return Redirect(GetRedirectUrl(model.ReturnUrl));
                }
            }

            //employee Login
            if (isValidEmployee != null)
            {
                var isPassworEmploeeValid = ValidatePassword(model.Password, isValidEmployee.Passsword);
                if (isPassworEmploeeValid)
                {
                    var identity = new ClaimsIdentity(new[]
                        {
                            new Claim("DisplayName",isValidEmployee.FullName),
                            new Claim(ClaimTypes.Name, isValidEmployee.FullName),
                            new Claim(ClaimTypes.Email, isValidEmployee.Email),
                            //new Claim("UserId", isValidEmployee.UserId.ToString()),
                             new Claim("UserId", isValidEmployee.EmployeeId.ToString()),
                            new Claim("EmployeeId", isValidEmployee.EmployeeId.ToString()),
                            new Claim("ClientId", isValidEmployee.ClientId.ToString()),
                            new Claim("CompanyId", isValidEmployee.CompanyId.ToString())
                        },
                        "ApplicationCookie");                 
                        identity.AddClaim(new Claim(ClaimTypes.Role, "Employee"));
                  

                    //identity.AddClaim(new Claim(ClaimTypes.Role, "OmniUser"));
                    var ctx = Request.GetOwinContext();
                    var authManager = ctx.Authentication;

                    authManager.SignIn(identity);

                    return Redirect(GetRedirectUrl(model.ReturnUrl));
                }
            }//Employee Login Ends Here
            

            // user authN failed
            ModelState.AddModelError("Email", "Invalid email or password Or your subscription might have ended");
            return View();
        }

        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("UserSel", "User");
            }

            return returnUrl;
        }


        public ActionResult LogOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut("ApplicationCookie");
            return RedirectToAction("index", "home");
        }

        private bool ValidatePassword(string password, string correctHash)
        {
            return BCrypt.Net.BCrypt.Verify(password, correctHash);
        }




    }


}

Payroll/Payroll/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.Controllers
{
    public class LeaveController : Controller
    {
        // GET: Leave
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateLeave()
        {           
           return PartialView("~/Views/Leave/_CreateLeave.cshtml");           
        }

        public ActionResult LeaveSel()
        {
            return View();
        }
        public ActionResult EmployeeLeaveCreate()
        {
            return View();
        }


    }
}

Payroll/Payroll/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.Controllers
{
  
    public class SalaryController : Controller
    {
        // GET: Salary
        public ActionResult SalaryRateSetup()
        {
            return View();
        }

        public ActionResult AddSalaryRate()
        {
            return PartialView("~/Views/Salary/_AddSalaryRate.cshtml");
        }

        public ActionResult EmployeeSalary()
        {
            return View();
        }

        public ActionResult DispatchSalary()
        {
            return PartialView("~/Views/Salary/_DispatchSalary.cshtml");
        }
    }
}

Payroll/Payroll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @*needs to be Bundled and minified*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-glyphicons.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.rtl.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.default.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.default.mobile.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.common.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Toastr/toastr.css" rel="stylesheet" />


    @*Scirpts sections is loaded at first since kendo and jqeury is not recognized while app is running*@
    @*Needs to be bundled and minified as well*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/Validator/jquery.validate.js"></script>
    <script src="~/scripts/Validator/jquery.validate.unobtrusive.js"></script>
    <script src="~/scripts/Kendo/jszip.min.js"></script>
    <script src="~/scripts/Kendo/kendo.all.min.js"></script>
    <script src="~/scripts/Kendo/console.js"></script>
    <script>
        var WebApiUri = '@System.Configuration.ConfigurationManager.AppSettings["WebApiUri"]'
    </script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>  @Html.ActionLink("Logout", "LogOut", "Auth", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    <script src="~/Scripts/bootstrap.min.js"></script>
    
    <script src="~/scripts/Toastr/toastr.js"></script>
</body>
</html>

Payroll/Payroll/Views/Shared/_TestLayout.cshtml
@using System.Web.Optimization

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="SHORTCUT ICON" href="~/Content/Logo/favicon.ico" />
    @*needs to be Bundled and minified*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-glyphicons.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.rtl.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.custom.css" rel="stylesheet" />
    @*<link href="~/Content/Kendo/kendo.default.min.css" rel="stylesheet" />*@
    <link href="~/Content/Kendo/kendo.default.mobile.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.common.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Toastr/toastr.css" rel="stylesheet" />

    @*Scirpts sections is loaded at first since kendo and jqeury is not recognized while app is running*@
    @*Needs to be bundled and minified as well*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/Validator/jquery.validate.js"></script>
    <script src="~/scripts/Validator/jquery.validate.unobtrusive.js"></script>
    <script src="~/scripts/Kendo/jszip.min.js"></script>
    <script src="~/scripts/Kendo/kendo.all.min.js"></script>
    <script src="~/scripts/Kendo/console.js"></script>
    <script src="~/scripts/Utility/Utility.js"></script>
    <script>
        var WebApiUri = '@System.Configuration.ConfigurationManager.AppSettings["WebApiUri"]'
    </script>
    <script src="~/scripts/BlockUi/BlockUi.js"></script>
    <script src="~/scripts/BlockUi/BlockUiGif.js"></script>
    @Styles.Render("~/bundles/content/admin")
</head>

<body>
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <div class="page-container">
        <div class="sidebar-menu" style="width: 230px">
            <div class="sidebar-header" style="height: 80px">
                <a href="@Url.Action("Dashboard", "Auth")"> <img src="~/Content/Logo/IRASLOGO.png" style="width: 170px" /></a>
            </div>
            <div class="main-menu">
                <div class="menu-inner">
                    <nav>
                        <ul class="metismenu" id="menu">
                            <li>
                                <a href="@Url.Action("Dashboard", "Auth")" aria-expanded="true"><i class="ti-dashboard"></i><span>dashboard</span></a>
                            </li>
                            <li class="active">
                                <a href="javascript:void(0)" aria-expanded="true">
                                    <i class="ti-layout-sidebar-left"></i>
                                    <span>
                                        Report
                                    </span>
                                </a>
                                <ul class="collapse">
                                    <li><a href="@Url.Action("Company", "Company")">Company</a></li>
                                    <li><a href="@Url.Action("UserSel", "User")">User</a></li>
                                    <li><a href="@Url.Action("SalaryRateSetup", "Salary")">Salary Setup</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-pie-chart"></i><span>Employee</span></a>
                                <ul class="collapse">
                                    <li><a href="@Url.Action("EmployeeAttendence", "Attendence")">Attendence</a></li>
                                    <li><a href="@Url.Action("Employee", "Employee")">Employee</a></li>
                                    <li><a href="@Url.Action("EmployeeLeave", "Employee")">Leaves</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-pie-chart"></i><span>Leave</span></a>
                                <ul class="collapse">
                                    <li><a href="@Url.Action("LeaveSel", "Leave")">Create</a></li>
                                    <li><a href="@Url.Action("EmployeeLeaveCreate", "Leave")">Apply</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript:void(0)" aria-expanded="true">
                                <i class="ti-pie-chart"></i><span>Salary</span></a>
                                <ul class="collapse">
                                    <li><a href="@Url.Action("EmployeeSalary", "Salary")">Salary</a></li>

                                </ul>
                            </li>

                            @*<li>
                                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-palette"></i><span>Hourly Details</span></a>
                                <ul class="collapse">
                                    <li><a href="@Url.Action("ProjectDetails", "EstimationDetail")">Project Details</a></li>
                                    <li><a href="@Url.Action("SequenceDetails", "EstimationDetail")">Sequence Details</a></li>
                                    <li><a href="@Url.Action("ShotDetail", "EstimationDetail")">Shot Details</a></li>
                                </ul>
                            </li>*@
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="main-content">
            <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right" style="background:white">
                            <img class="avatar user-thumb" src="~/Content/Admin/Images/avatar.png" alt="avatar">
                            <h6 class="user-name dropdown-toggle" style="color: black" data-toggle="dropdown">@CurrentUser.DisplayName <i class="fa fa-angle-down"></i></h6>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="@Url.Action("LogOut", "Auth")"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="main-content-inner">
                @RenderBody()
            </div>

        </div>
        <footer>
            <div class="footer-area">
                <p>&copy; Copyright 2018. All right reserved. 
                <a href="http://www.incessantrain.com/">Incessant Rain Animation Studios</a>.</p>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/Toastr/toastr.js"></script>
    <script src="~/Content/Admin/js/popper.min.js"></script>
    <script src="~/Content/Admin/js/metisMenu.min.js"></script>
    <script src="~/Content/Admin/js/jquery.slimscroll.min.js"></script>
    <script src="~/Content/Admin/js/Chart.min.js"></script>
    <script src="~/Content/Admin/js/line-chart.js"></script>
    <script src="~/Content/Admin/js/scripts.js"></script>
</body>
</html>